name: machine_test_new
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  internet_connection_checker_plus: ^2.3.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.0.14
  equatable: ^2.0.5
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
